markdown: kramdown
highlighter: rouge
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

repository: https://github.com/featherweight/featherweight
help_url: https://github.com/featherweight/featherweight

tagline: "Featherweight: Application Framework for LabVIEWâ„¢"

collections:
  content:
    output: true

gems:
- jekyll-sitemap

exclude:
- "*.esproj"
- README.md

docs_menu:
- title: Getting Started
  items:
  - /docs/
  - /what-is-featherweight/
  - /philosophy/
  - /quickstart/
  - /testing/
  - /deployment/
  - /download/

- title: Featherweight Concepts
  items:
  - /concepts/actors/
  - /concepts/messaging/
  - /concepts/sockets/
  - /concepts/kernel/
  - /concepts/codegen/

- title: FTW Actor Libraries
  items:
  - /docs/actor-instance/
  - /docs/actor-inbox/
  - /docs/actor-connector/
  - /docs/actor-supervisor/
  - /docs/actor-message/
  - /docs/actor-job-scheduler/
  - /docs/actor-job/
  - /docs/actor-socket-publisher-subscriber/
  - /docs/actor-socket-producer-consumer/

- title: FTW Core Libraries
  items:
  - /docs/database-sqlite/
  - /docs/dataflow/
  - /docs/expressions/
  - /docs/error/
  - /docs/file-system/
  - /docs/json/
  - /docs/http-client/
  - /docs/http-server/
  - /docs/numeric/
  - /docs/reflection/
  - /docs/regex/
  - /docs/string/
  - /docs/system/
  - /docs/time/
  - /docs/dotnet/

- title: FTW Cookbook
  items:
  - /concepts/utilities/
  - /concepts/application-structure/
  - /concepts/actor-or-object/
  - /concepts/debugging-actors/
  - /concepts/json-tips/
  - /concepts/sqlite-tips/
  - /concepts/regex-tips/
  - /concepts/idiom-conversions/

- title: Meta
  items:
  - /contributors/
  - /governance/
  - /licensing/
  - /brand/
  - /releases/
