markdown: kramdown
highlighter: pygments
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

repository: https://github.com/featherweight/featherweight
help_url: https://github.com/featherweight/featherweight

tagline: "Featherweight: Application Framework for LabVIEWâ„¢"

collections:
  docs:
    output: true

gems:
- jekyll-sitemap

exclude:
 - "*.esproj"
 - README.md
 